name: CI/CD web Angular

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout do código
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🛠️ Build Angular para produção
        run: npm run build angularproject -- --configuration production

      - name: 🏷️ Obter versão do package.json
        id: project_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "Versão: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: 🐳 Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏗️ Build da imagem Docker do frontend
        run: docker build -t torresbento/tbmt-web-angular:${{ steps.project_version.outputs.version }} .

      - name: 🏷️ Taguear versão atual como latest
        run: |
          docker tag torresbento/tbmt-web-angular:${{ steps.project_version.outputs.version }} torresbento/tbmt-web-angular:latest
          docker push torresbento/tbmt-web-angular:latest

      - name: 📤 Push da imagem para Docker Hub
        run: docker push torresbento/tbmt-web-angular:${{ steps.project_version.outputs.version }}

      - name: 🚀 Deploy no servidor via SSH
        if: success()
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}      # IP público da EC2
          username: ${{ secrets.REMOTE_USER }}  # "ubuntu"
          key: ${{ secrets.SSH_KEY }}           # chave privada .pem
          port: 22                               # padrão SSH
          script: |
            echo "⛔ Parando container antigo..."
            sudo docker stop web-angular || true

            echo "🗑️ Removendo container antigo..."
            sudo docker rm web-angular || true
            

            echo "🧹 Removendo imagem antiga..."
            sudo docker image prune -a -f --filter "label=project=web-angular" || true

            echo "⬇️ Baixando nova imagem..."
            sudo docker pull torresbento/tbmt-web-angular:${{ steps.project_version.outputs.version }}

            echo "🌐 Garantindo rede personalizada (se necessário)..."
            if ! sudo docker network inspect bmt-rede-docker > /dev/null 2>&1; then
              sudo docker network create --driver bridge --subnet 172.18.0.0/16 bmt-rede-docker
            fi

            echo "🚀 Subindo novo container..."
            sudo docker run -d --name web-angular \
              --label project=web-angular \
              --network bmt-rede-docker \
              -p 4200:80 \
              torresbento/tbmt-web-angular:${{ steps.project_version.outputs.version }}
